language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO="Django==1.3.5"
  - DJANGO="Django==1.4.3"
  - DJANGO="git+git://github.com/django/django.git@master#egg=django"

# command to install dependencies
install: pip install -r requirements.txt

# command to run tests
script: python subscribeme/manage.py test
